### ISSUE TITLE
calling "destroy()" function crashes the app

### ISSUE THREAD

**Issue by StasDoskalenko** [splitio/react-native-client#38]
In newer RN versions they've finally removed deprecated `removeEventListener` function in favor of new instance-based remove() function call.

I've created a patch in our local project - the change seems to be working fine.

Would really appreciate if you can approve and merge this PR https://github.com/splitio/react-native-client/pull/37/files

**Comment by EmilianoSanchez** [comment]
Hi @StasDoskalenko , 

Thank you for the PR. We have merged it and will make a patch release as soon as possible, but need to validate a few dependency updates first.
I will let you know when the release is done.

**Comment by StasDoskalenko** [comment]
Thank you @EmilianoSanchez and @Tim020 !

**Comment by EmilianoSanchez** [comment]
@StasDoskalenko , React Native SDK v0.6.1 has been released, which includes your [PR](https://github.com/splitio/react-native-client/pull/37)
