### ISSUE TITLE
Support for React Native tv-os?

### ISSUE THREAD

**Issue by satriapr** [splitio/react-native-client#63]
Hi everyone, I have a question: does split.io support react-native-tvos? We are currently using react-native-tvos@0.64.2-4, but we are encountering an issue with RNsplit.

We receive the error: 
`Could not find the following native modules: RNSplit. Did you forget to run 'pod install'?
`

I attempted to add it manually in the Podfile, but I received the message: 
`The platform of the target 'sn_vps-tvOS' (tvOS 12.0) is not compatible with 'RNSplit (0.7.0)', which does not support 'tvOS'.`

Your assistance is greatly appreciated!

**Comment by hbqdev** [comment]
HI @satriapr 
At the moment our SDK doesn't support tv-os.

We apologize for the inconvenience.

Regards

**Comment by EmilianoSanchez** [comment]
Hi @satriapr 

As @hbqdev mentioned, at the moment the SDK doesn't support tvOS. However, we are planning to include support in the next release. 

There is no ETA yet for the release. In the meantime, you can try a release candidate by running `npm install @splitsoftware/splitio-react-native@0.7.1-rc.0`.

**Comment by EmilianoSanchez** [comment]
Closing the issue.

Version 0.8.0 of the [React Native SDK](https://www.npmjs.com/package/@splitsoftware/splitio-react-native) has been released, which extends support to tvOS and macOS.

CC: @satriapr  @hbqdev

**Comment by satriapr** [comment]
Hi @EmilianoSanchez @hbqdev thanks for your prompt replies. We've tested version 0.8.0, but unfortunately, we're still encountering the issue where RNSplit is not available.

On the other hand, version 0.7.1-rc.0 appears to be functioning correctly. Could you please confirm whether it would be safe to use this release candidate version in a production environment? Typically, we refrain from deploying release candidates into production.

Thanks!

**Comment by satriapr** [comment]
@EmilianoSanchez @hbqdev v0.8.0 is working fine with tvOS. Thanks for your support!
