### ISSUE TITLE
control treatment is returned even after isReady completes

### ISSUE THREAD

**Issue by djMax** [splitio/react-native-client#83]
I am waiting for the sdk.ready() promise to resolve, and then calling getTreatments (not immediately after, but in a test environment, it's pretty soon after). The control treatment is coming back, and this is an invalid treatment in my case because it's missing configuration information. I would expect the ready() promise not to resolve until the real treatments have been loaded. Is there an event that will do this?

**Comment by djMax** [comment]
@exploIF may have found the cause here, which is that in RN SDK, when you switch userId, it's not enough to use the same factory with a new client, you need an entirely new factory. Confusing I would suggest, but at least fixable.

**Comment by EmilianoSanchez** [comment]
Hi @djMax , 

If by switching the `userId` you mean retrieving a different client from the same factory instance (e.g., `const client = factory.client(OTHER_USER_ID);`), remember to call the `ready()` promise of the corresponding client. 
For example:

```javascript
import { SplitFactory } from '@splitsoftware/splitio-react-native';

const factory = SplitFactory({
  core: {
    authorizationKey: 'YOUR_SDK_KEY',
    key: 'id_1'
  }
});

const clientForId1 = factory.client(); // same than calling `factory.client('id_1');`

const clientForId2 = factory.client('id_2');

clientForId1.ready().then(() => { 
  const treatment = clientForId1.getTreatment(MY_FEATURE_FLAG); // should not be control if MY_FEATURE_FLAG exists
});

clientForId2.ready().then(() => { 
  const treatment = clientForId2.getTreatment(MY_FEATURE_FLAG); // should not be control if MY_FEATURE_FLAG exists
});
```

**Comment by djMax** [comment]
Yeah, that's what I had originally, but it did not work. There is some time AFTER ready() fires for the second client where the treatments are all the control treatments in the new client. If I create a new factory, this does not happen.

**Comment by EmilianoSanchez** [comment]
If that's the case @djMax , I would appreciate if you can share some code snippet to replicate it, because it would be a bug on the SDK. However, I wasn't able to replicate that behaviour on my side.
